Strip ASCII "nul" character (0x00) from text before filtering on it
Running a query with this character in it in a `where` clause will
cause a

```
ValueError: A string literal cannot contain NUL (0x00) characters.
```

From Django's postgres backend.  We have to strip these characters out
manually.